### ISSUE TITLE
Add the github actions

### ISSUE THREAD

**Issue by Hend-t** [hend-isleem/drug_overdose#28]
Add the github actions to the repo

**Comment by Hend-t** [comment]
Created a GitHub action to run the tests once any code is pushed or Pr is opened on the following branches
[main, back-end, tests-for-backend]

**Comment by Hend-t** [comment]
The actions run but there is an issue with setting the environment variables which contain sensitive data

**Comment by Hend-t** [comment]
Added an action to run Redis and set up the variables in the repo secrets and access them as GitHub variables for the development environment.

However, the test command is still failing on GitHub actions due to a certain variable not being accessed correctly

**Comment by Hend-t** [comment]
This is still work in progress

**Comment by hendisleem-gordian** [comment]
Git hub actions are working accurately and it's even passed for the front-end branch.
