### ISSUE TITLE
Test out the API calls and data via postman

### ISSUE THREAD

**Issue by Hend-t** [hend-isleem/drug_overdose#5]
Test out the API calls via Postman to see if we need to request any access, if we need any keys, and what the status of the requests is.

**Comment by Hend-t** [comment]
I contacted DrugBank yesterday to apply for a research API key so we can use the API freely

**Comment by Hend-t** [comment]
I tried and validated the response of the `RxNorm` API via Postman

**Comment by hendisleem-gordian** [comment]
@PeterWadie  has taken over this task and contacted the company in issue #3
